version: '3'
services:
    #Postgres
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
            
    #nginix
    simple-blog-api:
        depends_on:
            - postgres
        image: geetha200692/simple-blog
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api